import { YoutubeVideo } from './youtube';

// Mock data with specific YouTube videos from Kunal Kamra's channel
export const mockYoutubeVideos: YoutubeVideo[] = [
  {
    id: "jY-NoAWPZ6Y",
    title: "Travelling with my Parents | Stand Up Comedy by Kunal Kamra",
    description: "In this clip from Kunal Kamra's stand-up special, he talks about his experiences travelling with his parents.",
    publishedAt: "2023-10-15T14:30:00Z",
    thumbnail: "https://i.ytimg.com/vi/jY-NoAWPZ6Y/maxresdefault.jpg",
    views: "2.3M",
    likes: "156K",
    embedId: "jY-NoAWPZ6Y",
    category: "Stand-up",
  },
  {
    id: "vva7jReRA7w",
    title: "The Billionaire Monopoly | Stand Up Comedy By Kunal Kamra",
    description: "Kunal Kamra talks about billionaire monopolies in this stand-up comedy set.",
    publishedAt: "2023-05-22T09:15:00Z",
    thumbnail: "https://i.ytimg.com/vi/vva7jReRA7w/maxresdefault.jpg",
    views: "1.8M",
    likes: "145K",
    embedId: "vva7jReRA7w",
    category: "Stand-up",
  },
  {
    id: "w_nIjTqjYss",
    title: "Family members outside India | Stand Up Comedy by Kunal Kamra",
    description: "Kunal Kamra on family members who live outside India and their behavior when they visit.",
    publishedAt: "2022-08-05T18:45:00Z",
    thumbnail: "https://i.ytimg.com/vi/w_nIjTqjYss/maxresdefault.jpg",
    views: "976K",
    likes: "87K",
    embedId: "w_nIjTqjYss",
    category: "Stand-up",
  },
  {
    id: "2PnbFqm1vUY",
    title: "Indian Parents and their Complaints | Stand up Comedy by Kunal Kamra",
    description: "Kunal Kamra talks about the funny side of Indian parents and their complaints in this stand-up comedy clip.",
    publishedAt: "2022-07-12T12:00:00Z",
    thumbnail: "https://i.ytimg.com/vi/2PnbFqm1vUY/maxresdefault.jpg",
    views: "1.5M",
    likes: "121K",
    embedId: "2PnbFqm1vUY",
    category: "Stand-up",
  },
  {
    id: "3Su_ydENa2w",
    title: "When Politicians Tweet | Stand Up Comedy By Kunal Kamra",
    description: "Kunal Kamra on politicians and their social media presence in this hilarious stand-up comedy set.",
    publishedAt: "2022-06-18T15:30:00Z",
    thumbnail: "https://i.ytimg.com/vi/3Su_ydENa2w/maxresdefault.jpg",
    views: "3.2M",
    likes: "245K",
    embedId: "3Su_ydENa2w",
    category: "Stand-up",
  },
  {
    id: "qBbpFGGAkmo",
    title: "Honest Interview with Rahul Gandhi | Kunal Kamra",
    description: "Kunal Kamra sits down with Rahul Gandhi for an unfiltered conversation about politics and more.",
    publishedAt: "2022-01-25T10:20:00Z",
    thumbnail: "https://i.ytimg.com/vi/qBbpFGGAkmo/maxresdefault.jpg",
    views: "4.5M",
    likes: "276K",
    embedId: "qBbpFGGAkmo",
    category: "Interview",
  },
  {
    id: "cVkUWLDOzaw",
    title: "Engineering vs. MBA | Stand Up Comedy by Kunal Kamra",
    description: "In this comedy set, Kunal Kamra discusses the differences between engineering and MBA graduates.",
    publishedAt: "2021-04-14T08:00:00Z",
    thumbnail: "https://i.ytimg.com/vi/cVkUWLDOzaw/maxresdefault.jpg",
    views: "2.1M",
    likes: "186K",
    embedId: "cVkUWLDOzaw",
    category: "Stand-up",
  },
  {
    id: "yAgXsAce4y8",
    title: "Mumbai vs Delhi | Stand Up Comedy By Kunal Kamra",
    description: "Kunal Kamra presents a hilarious take on the differences between Mumbai and Delhi.",
    publishedAt: "2021-03-03T16:45:00Z",
    thumbnail: "https://i.ytimg.com/vi/yAgXsAce4y8/maxresdefault.jpg",
    views: "1.9M",
    likes: "147K",
    embedId: "yAgXsAce4y8",
    category: "Stand-up",
  },
  {
    id: "cisXPzAKnUA",
    title: "Shutup Ya Kunal - Episode 8 : Kanhaiya Kumar and Umar Khalid",
    description: "In this episode of his podcast, Kunal interviews Kanhaiya Kumar and Umar Khalid about student politics and current issues.",
    publishedAt: "2020-12-20T20:30:00Z",
    thumbnail: "https://i.ytimg.com/vi/cisXPzAKnUA/maxresdefault.jpg",
    views: "2.8M",
    likes: "209K",
    embedId: "cisXPzAKnUA",
    category: "Interview",
  },
  {
    id: "GW3B6csIc9I",
    title: "The State of Indian Media | Stand Up Comedy by Kunal Kamra",
    description: "Kunal Kamra breaks down the current state of Indian media with his signature style.",
    publishedAt: "2020-11-17T14:15:00Z",
    thumbnail: "https://i.ytimg.com/vi/GW3B6csIc9I/maxresdefault.jpg",
    views: "3.9M",
    likes: "328K",
    embedId: "GW3B6csIc9I",
    category: "Stand-up",
  },
  {
    id: "4QPAsssHGCQ",
    title: "Honest Restaurant Server | Stand Up Comedy By Kunal Kamra",
    description: "Kunal Kamra imagines what it would be like if restaurant servers were brutally honest.",
    publishedAt: "2020-10-22T11:00:00Z",
    thumbnail: "https://i.ytimg.com/vi/4QPAsssHGCQ/maxresdefault.jpg",
    views: "1.6M",
    likes: "134K",
    embedId: "4QPAsssHGCQ",
    category: "Stand-up",
  },
  {
    id: "rRgDfgyQMuM",
    title: "The Woke Joke - National Tour | Kunal Kamra Live",
    description: "Highlights from Kunal Kamra's national tour 'The Woke Joke' with his best political comedy bits.",
    publishedAt: "2020-09-05T19:00:00Z",
    thumbnail: "https://i.ytimg.com/vi/rRgDfgyQMuM/maxresdefault.jpg",
    views: "1.2M",
    likes: "96K",
    embedId: "rRgDfgyQMuM",
    category: "Live Show",
  },
  {
    id: "dkml-HbmkaM",
    title: "Shutup Ya Kunal - Episode 9 : Republic TV",
    description: "In this episode of his satirical talk show, Kunal Kamra takes on Republic TV and discussions around media ethics.",
    publishedAt: "2020-07-31T15:30:00Z",
    thumbnail: "https://i.ytimg.com/vi/dkml-HbmkaM/maxresdefault.jpg",
    views: "3.5M",
    likes: "297K",
    embedId: "dkml-HbmkaM",
    category: "Interview",
  }
];

// Function to simulate an API call with delay
export const fetchMockVideos = (delay = 1000): Promise<YoutubeVideo[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockYoutubeVideos);
    }, delay);
  });
};